### ISSUE TITLE
Cannot discover characteristics

### ISSUE THREAD

**Issue by edelibasi** [l0gg3r/LGBluetooth#2]
When I run the code only thing outputted is this:
2015-09-01 11:44:22.415 LGBluetoothExample[6344:762493] Connection with error - (null)
2015-09-01 11:44:22.714 LGBluetoothExample[6344:762493] Service discovered - FFE0

Is there something I'm missing? Could do with a bit of insight on this.

**Comment by sureshjoshi** [comment]
@edelibasi Did this get solved? Is there any associated code?

**Comment by edelibasi** [comment]
Hi Suresh,

I got it working thank you for your response.

**Comment by sureshjoshi** [comment]
No problem  :) Could you please close this issue as well?

Thanks!
