### ISSUE TITLE
How can we scan indefinitely, and get a callback on each advertisement?

### ISSUE THREAD

**Issue by sureshjoshi** [l0gg3r/LGBluetooth#5]
As the question asks, how can we scan indefinitely, and get a callback on each advertisement?

The scanWithPeripherals() call doesn't have any callbacks on device discovery. Also, I can't see any way to otherwise get some advertisement discovery information (other to maybe put a KVO on the peripherals variable?)

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <[LGBluetooth] How can we scan indefinitely, and get a callback on each advertisement? (#5)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by l0gg3r** [comment]
you can put a KVO, or you can just modify that part and send a pull request

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <Re: [LGBluetooth] How can we scan indefinitely, and get a callback on each advertisement? (#5)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sureshjoshi** [comment]
Thanks! I was hoping there was something internally that I didn't know about, but I'll try a few things out and see if I can get them working.
