### ISSUE TITLE
Sequential 'connects' fail

### ISSUE THREAD

**Issue by sureshjoshi** [l0gg3r/LGBluetooth#6]
I'm using a workflow where I end up in a view controller with a 'connect' and 'disconnect' button.

I can always connect/disconnect on the first attempt, however, subsequent attempts never connect. I need to go back to my listview, in order to re-scan for peripherals - and then try to connect again later when the peripheral has been re-discovered.

What could be going on?

Thanks!
-SJ

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <[LGBluetooth] Sequential 'connects' fail (#6)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Ging3rMonkey** [comment]
The disconnect removes the peripheral from the scanned list. If you want to reconnect to the peripheral you must rescan for it.

**Comment by tulurira** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

tulurira3@naver.com 님께 보내신 메일 <Re: [LGBluetooth] Sequential 'connects' fail (#6)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by sureshjoshi** [comment]
@Ging3rMonkey Thanks for that - I just noticed that while debugging this morning - any easy workaround? I was wondering if I should try to use the retrievePeripheralsWithIdentifiers API.

Also, do you know why it would be removed from that list after disconnection? I'm not entirely sure what the incentive is to remove it from that list..

**Comment by sureshjoshi** [comment]
Also: Just tried this and it worked - but not entirely sure of the long-term consequences (in LGCentralManager.m line 243)

```
- (void)centralManager:(CBCentralManager *)central didDisconnectPeripheral:(CBPeripheral *)peripheral
             error:(NSError *)error
{
    dispatch_async(dispatch_get_main_queue(), ^{
        LGPeripheral *lgPeripheral = [self wrapperByPeripheral:peripheral];
        [lgPeripheral handleDisconnectWithError:error];
        //        [self.scannedPeripherals removeObject:lgPeripheral];
    });
}
```

**Comment by Ging3rMonkey** [comment]
@sureshjoshi I was going to recommend what you did. I think you should be good.

**Comment by l0gg3r** [comment]
hm.. I think this should work, you can also use `retrievePeripheralsWithIdentifiers`

**Comment by sureshjoshi** [comment]
@l0gg3r So, do you think I should do a retrievePeripheralsWithIdentifiers after a disconnect? 

Is there anything that could happen by removing this line? 

```
//        [self.scannedPeripherals removeObject:lgPeripheral];
```
